name: 'Custom Node.js Setup Action'
description: 'Custom action for setting up Node.js environment'
inputs:
  package-json-path:
    description: 'Path from root directory to package.json file'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:

    - name: Step 1 - Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Step 2 - Cache Node.js dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Step 3 - Install Dependencies
      run: |
        cd ${{ inputs.package-json-path }}
        npm install
      shell: bash
