name: Backend Continuous Integration

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Python Dependencies Installation
        uses: ./actions/PyDepend_Action
        with:
          Pipfile-path: 'backend'

      - name: code linting
        uses: py-actions/flake8@v2
        with:
          ignore: "E501"   #ignores error E501 which flags any lines >79 characters

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run tests using pyTest
        run: |
          pip install pytest
          cd backend && pytest


  docker_build:
    runs-on: ubuntu-latest

    needs: [lint, test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          
      - name: Build Docker image
        run: |
          cd backend
          docker build --tag mp-backend:latest .
