name: Backend Continuous Integration

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: cd backend && pipenv install

      - name: Run linter
        run: cd backend && pipenv run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: cd backend && pipenv install

      - name: Run tests
        run: cd backend && pipenv run test

  local_run:
    runs-on: ubuntu-latest

    needs: [lint, test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: cd backend && pipenv install

      - name: Run application locally
        run: cd backend && pipenv run serve

  docker_build_and_run:
    runs-on: ubuntu-latest

    needs: [lint, test, local_run]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          
      - name: Build Docker image
        run: |
          cd backend
          docker build --tag mp-backend:latest .

      - name: Run Docker container
        run: docker run -p 5000:5000 --name mp-backend -d mp-backend

      - name: Check the running application
        run: curl http://localhost:5000/movies

      - name: Review logs
        run: docker logs -f mp-backend

      - name: Stop the application
        run: docker stop mp-backend
