name: Frontend Continuous Integration

on:
  workflow_dispatch:

jobs:
  LINT_JOB:
    runs-on: ubuntu-latest
    steps:
      - name: NodeJS Environment Setup
        uses: Chady00/Movie-Picture-Pipeline@main
        with:
          package-json-path: 'frontend'
      - name: Running Lint
        run: cd frontend && npm run lint
      - name: Completed
        run: echo "Environment + lint done"

  TEST_JOB:
    runs-on: ubuntu-latest
    steps:
      - name: NodeJS Environment Setup
        uses: Chady00/Movie-Picture-Pipeline@main
        with:
          package-json-path: 'frontend'
      - name: Running tests
        run: cd frontend && npm run test
      - name: Completed
        run: echo "Environment + tests done"

  BUILD_JOB:
    runs-on: ubuntu-latest
    needs: [LINT_JOB, TEST_JOB]
    steps:
      - name: NodeJS Environment Setup
        uses: Chady00/Movie-Picture-Pipeline@main
        with:
          package-json-path: 'frontend'
      - name: Build Docker Image
        run: cd frontend && docker build -t mp-frontend:latest .
      - name: Run Docker Image
        run: docker run -p 5000:5000 --name mp-frontend -d mp-frontend
      - name: Review Logs
        run: docker logs -f mp-frontend
      - name: Completed
        run: echo "Environment + tests + build done"
