name: Frontend Continuous Integration

on:
  workflow_dispatch:

jobs:
  LINT_JOB:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: NodeJS Environment Setup
        uses: ./actions/NodeJs_Action
        with:
          package-json-path: 'frontend'
      - name: Running Lint
        run: cd frontend && npm run lint
      - name: Completed
        run: echo "Environment + lint done"

  TEST_JOB:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: NodeJS Environment Setup
        uses: ./actions/NodeJs_Action
        with:
          package-json-path: 'frontend'
      - name: Running tests
        run: cd frontend && npm run test
      - name: Completed
        run: echo "Environment + tests done"

  BUILD_JOB:
    runs-on: ubuntu-latest
    needs: [LINT_JOB, TEST_JOB]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: NodeJS Environment Setup
        uses: ./actions/NodeJs_Action
        with:
          package-json-path: 'frontend'

      - name: Build Docker Image
        run: |
          cd frontend && docker build \
            --build-arg REACT_APP_MOVIE_API_URL=http://localhost:5000 \
            --tag mp-frontend:latest \
            ./frontend
          
      - name: Completed
        run: echo "Environment + build done"
