name: Frontend Continuous Deployment

on:
  workflow_dispatch:

jobs:
  Frontend-CD-EKS-Docker-AWS-ECR:
    runs-on: ubuntu-latest
    env:
      REACT_APP_MOVIE_API_URL: http://localhost:5000
      Path: 'frontend'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: NodeJS Environment Setup
        uses: ./actions/NodeJs_Action
        with:
          package-json-path: ${{ env.Path }}

      - name: Running Lint
        run: cd ${{ env.Path }} && npm run lint

      - name: Running tests
        run: cd ${{ env.Path }} && npm run test

      - name: Build Docker Image
        run: |
          docker build \
            --build-arg REACT_APP_MOVIE_API_URL=$REACT_APP_MOVIE_API_URL \
            --tag mp-${{ env.Path }}:latest \
            ./${{ env.Path }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: 482334913182.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: 482334913182.dkr.ecr.us-east-1.amazonaws.com/frontimage:github.sha

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Update AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          aws --version

      - name: Deploy to EKS
        run: |
          kustomize build ./${{ env.Path }}/k8s | kubectl apply -f -
